; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = default

[env]
platform = espressif32@6.5.0
framework = arduino
monitor_speed = 115200
lib_deps =
	nanopb/Nanopb@^0.4.3
	knolleary/PubSubClient @ ^2.8
	NeoPixelBus @ 2.6.9
	https://github.com/BlumAmir/TimeSyncClientArduino.git
	256dpi/MQTT @ ^2.4.8

[common]
build_flags =
	-DMQTT_MAX_PACKET_SIZE=25000
	-DMQTT_KEEPALIVE=5
	-DMQTT_SOCKET_TIMEOUT=5

[env:default]
board = seeed_xiao_esp32c3
build_flags =
	${common.build_flags}
	-DDATA_PIN=10
	-DTIME_SERVER_IP=\"10.0.1.200\"
	-DMQTT_BROKER_IP=\"10.0.1.200\"
	-DLED_OBJECT_SERVICE_IP=\"10.0.1.200\"
	-DLED_SEQ_SERVICE_IP=\"10.0.1.200\"
	-DINFLUXDB_IP=\"10.0.1.200\"
	-DLED_OBJECT_SERVICE_PORT=\"8081\"
	-DLED_SEQ_SERVICE_PORT=\"8082\"
	-DINFLUXDB_PORT=\"8086\"
	-DTIME_SYNC_DEBUG
; upload_protocol = espota
; upload_port = ring11.local
lib_deps =
	${env.lib_deps}
	; ../kivsee-render/
	https://github.com/KivSee/kivsee-render.git
	bblanchon/ArduinoJson@^6.18.3
	tobiasschuerg/ESP8266 Influxdb@3.9.0

[env:sapir]
board = esp32dev
build_flags =
	${common.build_flags}
	-DDATA_PIN=0
	-DTIME_SERVER_IP=\"192.168.1.9\"
	-DMQTT_BROKER_IP=\"192.168.1.9\"
	-DLED_OBJECT_SERVICE_IP=\"192.168.1.9\"
	-DLED_OBJECT_SERVICE_PORT=\"8081\"
	-DLED_SEQ_SERVICE_IP=\"192.168.1.9\"
	-DLED_SEQ_SERVICE_PORT=\"8082\"
	-DTIME_SYNC_DEBUG
upload_protocol = espota
upload_port = 192.168.1.18
lib_deps =
	${env.lib_deps}
	https://github.com/KivSee/kivsee-render.git
	bblanchon/ArduinoJson@^6.18.3
	tobiasschuerg/ESP8266 Influxdb@3.9.0

[env:bigler]
board = esp32dev
build_flags =
	${common.build_flags}
	-DDATA_PIN=2
	-DTIME_SERVER_IP=\"10.0.0.200\"
	-DMQTT_BROKER_IP=\"10.0.0.200\"
	-DLED_OBJECT_SERVICE_IP=\"10.0.0.200\"
	-DLED_SEQ_SERVICE_IP=\"10.0.0.200\"
	-DINFLUXDB_IP=\"10.0.0.200\"
	-DLED_OBJECT_SERVICE_PORT=\"8081\"
	-DLED_SEQ_SERVICE_PORT=\"8082\"
	-DINFLUXDB_PORT=\"8086\"
	-DTIME_SYNC_DEBUG
lib_deps =
	${env.lib_deps}
	https://github.com/KivSee/kivsee-render.git
	bblanchon/ArduinoJson@^6.18.3
	tobiasschuerg/ESP8266 Influxdb@3.9.0

[env:peacock]
board = esp32dev
build_flags =
	${common.build_flags}
	-DDATA_PIN=2
	-DTIME_SERVER_IP=\"10.0.1.200\"
	-DMQTT_BROKER_IP=\"10.0.1.200\"
	-DLED_OBJECT_SERVICE_IP=\"10.0.1.200\"
	-DLED_OBJECT_SERVICE_PORT=\"8081\"
	-DLED_SEQ_SERVICE_IP=\"10.0.1.200\"
	-DLED_SEQ_SERVICE_PORT=\"8082\"
	-DINFLUXDB_IP=\"10.0.1.200\"
	-DINFLUXDB_PORT=\"8086\"
	-DTIME_SYNC_DEBUG
; upload_protocol = espota
; upload_port = 10.0.0.17
lib_deps =
	${env.lib_deps}
	; ../kivsee-render/
	https://github.com/KivSee/kivsee-render.git
	bblanchon/ArduinoJson@^6.18.3
	tobiasschuerg/ESP8266 Influxdb@3.9.0
