; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = default

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps = 
	nanopb/Nanopb@^0.4.3
	knolleary/PubSubClient @ ^2.8
	NeoPixelBus
	https://github.com/BlumAmir/TimeSyncClientArduino.git
	googlecloudplatform/Google Cloud IoT Core JWT @ ^1.1.11
	256dpi/MQTT @ ^2.4.8

[common]
build_flags = 
	-DMQTT_MAX_PACKET_SIZE=25000
	-DMQTT_KEEPALIVE=5
	-DMQTT_SOCKET_TIMEOUT=5

[env:default]
board = esp32doit-devkit-v1
build_flags = 
	${common.build_flags}
	-DNUM_LEDS=33
	-DDATA_PIN=2
	-DTIME_SERVER_IP=\"192.168.1.26\"
	-DMQTT_BROKER_IP=\"192.168.1.26\"
	-DHTTP_SERVER_IP=\"192.168.1.26\"
	-DTIME_SYNC_DEBUG
lib_deps = 
	${env.lib_deps}
	https://github.com/blumamir/kivsee-render.git
	bblanchon/ArduinoJson@^6.18.3

[env:sapir]
board = esp32dev
build_flags = 
	${common.build_flags}
	-DNUM_LEDS=200
	-DDATA_PIN=0
	-DTIME_SERVER_IP=\"192.168.1.18\"
	-DMQTT_BROKER_IP=\"192.168.1.26\"
	-DHTTP_SERVER_IP=\"192.168.1.26\"
	-DTIME_SYNC_DEBUG
upload_port = /dev/cu.SLAB_USBtoUART
monitor_port = /dev/cu.SLAB_USBtoUART
lib_deps = 
	${env.lib_deps}
	../kivsee-render/
	bblanchon/ArduinoJson@^6.18.3

[env:bigler]
board = esp32dev
build_flags = 
	${common.build_flags}
	-DNUM_LEDS=33
	-DDATA_PIN=2
	-DTIME_SERVER_IP=\"10.0.0.200\"
	-DMQTT_BROKER_IP=\"10.0.0.200\"
	-DHTTP_SERVER_IP=\"10.0.0.37\"
	-DTIME_SYNC_DEBUG
	-DMQTT_BROKER_MOSQITTO
lib_deps = 
	${env.lib_deps}
	https://github.com/blumamir/kivsee-render.git
	bblanchon/ArduinoJson@^6.18.3
