// source: animation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var effects_pb = require('./effects_pb.js');
goog.object.extend(proto, effects_pb);
goog.exportSymbol('proto.TimedAnimationProto', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TimedAnimationProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.TimedAnimationProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.TimedAnimationProto.displayName = 'proto.TimedAnimationProto';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TimedAnimationProto.prototype.toObject = function(opt_includeInstance) {
  return proto.TimedAnimationProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TimedAnimationProto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimedAnimationProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    animation: (f = msg.getAnimation()) && effects_pb.AnimationProto.toObject(includeInstance, f),
    triggerName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    startTimeMsSinceEpoch: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TimedAnimationProto}
 */
proto.TimedAnimationProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TimedAnimationProto;
  return proto.TimedAnimationProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TimedAnimationProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TimedAnimationProto}
 */
proto.TimedAnimationProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new effects_pb.AnimationProto;
      reader.readMessage(value,effects_pb.AnimationProto.deserializeBinaryFromReader);
      msg.setAnimation(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTriggerName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setStartTimeMsSinceEpoch(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TimedAnimationProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TimedAnimationProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TimedAnimationProto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TimedAnimationProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnimation();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      effects_pb.AnimationProto.serializeBinaryToWriter
    );
  }
  f = message.getTriggerName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStartTimeMsSinceEpoch();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
};


/**
 * optional AnimationProto animation = 1;
 * @return {?proto.AnimationProto}
 */
proto.TimedAnimationProto.prototype.getAnimation = function() {
  return /** @type{?proto.AnimationProto} */ (
    jspb.Message.getWrapperField(this, effects_pb.AnimationProto, 1));
};


/**
 * @param {?proto.AnimationProto|undefined} value
 * @return {!proto.TimedAnimationProto} returns this
*/
proto.TimedAnimationProto.prototype.setAnimation = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.TimedAnimationProto} returns this
 */
proto.TimedAnimationProto.prototype.clearAnimation = function() {
  return this.setAnimation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.TimedAnimationProto.prototype.hasAnimation = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string trigger_name = 2;
 * @return {string}
 */
proto.TimedAnimationProto.prototype.getTriggerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.TimedAnimationProto} returns this
 */
proto.TimedAnimationProto.prototype.setTriggerName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint64 start_time_ms_since_epoch = 3;
 * @return {number}
 */
proto.TimedAnimationProto.prototype.getStartTimeMsSinceEpoch = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.TimedAnimationProto} returns this
 */
proto.TimedAnimationProto.prototype.setStartTimeMsSinceEpoch = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


goog.object.extend(exports, proto);
