/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3 */

#ifndef PB_ANIMATION_PB_H_INCLUDED
#define PB_ANIMATION_PB_H_INCLUDED
#include <pb.h>
#include "effects.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _TimedAnimationProto {
    pb_callback_t animation;
    pb_callback_t trigger_name;
    uint64_t start_time_ms_since_ephoc;
} TimedAnimationProto;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TimedAnimationProto_init_default         {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define TimedAnimationProto_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TimedAnimationProto_animation_tag        1
#define TimedAnimationProto_trigger_name_tag     2
#define TimedAnimationProto_start_time_ms_since_ephoc_tag 3

/* Struct field encoding specification for nanopb */
#define TimedAnimationProto_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  animation,         1) \
X(a, CALLBACK, SINGULAR, STRING,   trigger_name,      2) \
X(a, STATIC,   SINGULAR, UINT64,   start_time_ms_since_ephoc,   3)
#define TimedAnimationProto_CALLBACK pb_default_field_callback
#define TimedAnimationProto_DEFAULT NULL
#define TimedAnimationProto_animation_MSGTYPE AnimationProto

extern const pb_msgdesc_t TimedAnimationProto_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TimedAnimationProto_fields &TimedAnimationProto_msg

/* Maximum encoded size of messages (where known) */
/* TimedAnimationProto_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
